package main

import (
	"encoding/json"
	"io"

	"github.com/peterbourgon/gokit/server"
	"golang.org/x/net/context"
)

// jsonCodec could be autogenerated from type Add.
type jsonCodec struct{}

// Decode TODO
func (jsonCodec) Decode(_ context.Context, src io.Reader) (server.Request, error) {
	var addReq Request
	err := json.NewDecoder(src).Decode(&addReq)
	return addReq, err
}

// Encode TODO
func (jsonCodec) Encode(dst io.Writer, resp server.Response) error {
	return json.NewEncoder(dst).Encode(resp)
}
