package main

import (
	"encoding/json"
	"io"

	"github.com/peterbourgon/gokit/server"
	"golang.org/x/net/context"
)

// jsonCodec could be autogenerated from type Add.
type jsonCodec struct{}

// Decode TODO
func (c jsonCodec) Decode(_ context.Context, src io.Reader) (server.Request, error) {
	var addReq Request
	if err := json.NewDecoder(src).Decode(&addReq); err != nil {
		return nil, err
	}
	return addReq, nil
}

// Encode TODO
func (c jsonCodec) Encode(dst io.Writer, resp server.Response) error {
	addResp, ok := resp.(Response)
	if !ok {
		return server.ErrBadCast
	}
	return json.NewEncoder(dst).Encode(addResp)
}
