package main

import (
	"github.com/peterbourgon/gokit/server"
	"golang.org/x/net/context"
)

// makeEndpoint could be autogenerated from type Add.
func makeEndpoint(a Add) server.Endpoint {
	return func(ctx context.Context, req server.Request) (server.Response, error) {
		addReq, ok := req.(Request)
		if !ok {
			return nil, server.ErrBadCast
		}

		v := a(ctx, addReq.A, addReq.B)
		return Response{v}, nil
	}
}
