package main

// Request could be autogenerated from type Add.
type Request struct {
	A int `json:"a"`
	B int `json:"b"`
}

// Response could be autogenerated from type Add.
type Response struct {
	V int `json:"v"`
}
