// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package zipkinquery

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"zipkincore"
	"zipkindependencies"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = zipkincore.GoUnusedProtection__
var _ = zipkindependencies.GoUnusedProtection__

func init() {
}
