package server

import (
	"encoding/json"
	"io"

	"golang.org/x/net/context"
)

// Add is a function that takes two ints and returns an int.
type Add func(context.Context, int, int) int

// PureAdd is a pure service and can ignore the context.
func PureAdd(_ context.Context, a, b int) int { return a + b }

// AddViaResource is a non-pure service and must use the context.
func AddViaResource(r Resource) func(context.Context, int, int) int {
	return func(ctx context.Context, a, b int) int {
		return PureAdd(ctx, r.GetA(ctx, a), b)
	}
}

// Resource TODO
type Resource struct{}

// GetA TODO
func (r Resource) GetA(ctx context.Context, a int) int {
	return a
}

// AddRequest can be autogenerated.
type AddRequest struct {
	A int `json:"a"`
	B int `json:"b"`
}

// AddResponse can be autogenerated.
type AddResponse struct {
	V int `json:"v"`
}

// AddService can be autogenerated.
func AddService(a Add) Service {
	return func(ctx context.Context, req Request) (Response, error) {
		addReq, ok := req.(AddRequest)
		if !ok {
			return nil, ErrBadCast
		}

		v := a(ctx, addReq.A, addReq.B)
		return AddResponse{v}, nil
	}
}

// AddCodecJSON can be autogenerated.
type AddCodecJSON struct{}

// Decode TODO
func (c *AddCodecJSON) Decode(_ context.Context, src io.Reader) (Request, error) {
	var req AddRequest
	if err := json.NewDecoder(src).Decode(&req); err != nil {
		return nil, err
	}
	return req, nil
}

// Encode TODO
func (c *AddCodecJSON) Encode(dst io.Writer, resp Response) error {
	addResp, ok := resp.(AddResponse)
	if !ok {
		return ErrBadCast
	}
	return json.NewEncoder(dst).Encode(addResp)
}
