// Autogenerated code, do not change directly.
// To make changes to this file, please modify the templates at /gen-cmd/*.tmpl
package process

import (
	"golang.org/x/net/context"

	"github.com/go-kit/kit/endpoint"
)

type ProcessRequest struct {
	Number int
	Head   string
	Tails  string
}

type ProcessResponse struct {
	Ret string
}

func ProcessEndpoint(ctx context.Context, request interface{}) (interface{}, error) {
	req, ok := request.(ProcessRequest)
	if !ok {
		return nil, endpoint.ErrBadCast
	}
	ret, err := pureProcess(ctx, req.Number, req.Head, req.Tails)
	if err != nil {
		return nil, err
	}
	return ProcessResponse{Ret: ret}, nil
}
